version: "3.8"
services:
  nodejs:
    container_name: nodejs_puppeteer_server
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 6688:6688
    command:
      - node
      - src/main.js
